services:
  - type: web
    name: backend-rezeptapp
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d0h237be5dus73aq2trg-a.oregon-postgres.render.com:5432/elhassanmahmoud_db
      - key: DB_USERNAME
        value: elhassanmahmoud
      - key: DB_PASSWORD
        value: Ra06Qpk42kCvkbbMS3ddFFbLp26pTWbo
    ports:
      - 8080