services:
  - type: web
    name: backend-rezeptapp
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://dpg-d1bebl6uk2gs739mh4vg-a.oregon-postgres.render.com:5432/elhassanmahmoud_db_1zbb
      - key: DB_USERNAME
        value: elhassanmahmoud
      - key: DB_PASSWORD
        value: gu8g0NdPhMW4Lp7WnPTWvTYUNvBlSacQ
    ports:
      - 8080