services:
  - type: web
    name: backend-rezeptapp
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: DB_URL
        fromEnvVar: DB_URL
      - key: DB_USERNAME
        fromEnvVar: DB_USERNAME
      - key: DB_PASSWORD
        fromEnvVar: DB_PASSWORD
    ports:
      - 8080